### PR TITLE
Sorting an Array in Descending Order

### PR DESCRIPTION
**Pull request by ManoCoder**
In this program, we need to sort the given array in descending order such that elements will be arranged from largest to smallest. This can be achieved through two loops. Outer loop will select a element and inner loop allow us to compare selected element with rest of the elements.

### CODE REVIEW

**Review by Himanshu40 — CHANGES_REQUESTED** [review]
I saw you have sorted an array but this repo is all about adding algorithms on how to sort anything. Btw which sorting algo you have applied to sort the array?

**Comment by ManoCoder** [comment]
Algorithm
Declare and initialize an array.
Loop through the array and select an element.
Inner loop will be used to compare selected element from outer loop with rest of the elements of array.
If any element is greater than the selected element then swap the values.
Continue this process till entire list is sorted in descending order.

**Comment by Himanshu40** [comment]
> Algorithm Declare and initialize an array. Loop through the array and select an element. Inner loop will be used to compare selected element from outer loop with rest of the elements of array. If any element is greater than the selected element then swap the values. Continue this process till entire list is sorted in descending order.

Yeah, I know that but type of sorting like see there is bucket sort, merge sort, insertion sort, etc. So you only have to add the algorithm. If you are unaware, have a look into the issues list I have provided https://github.com/Himanshu40/Sorting-Algorithm/issues

**Comment by ManoCoder** [comment]
Gotcha using insertion sort we could do that:
Algorithm:
START
Step 1 : If it is the first element, it is already sorted. return 1;
Step 2 : Pick next element
Step 3 : Compare with all elements in the sorted sub-list
Step 4 : Shift all the elements in the sorted sub-list that is less than the 
value to be sorted
Step 5 : Insert the value
Step 6 : Repeat until list is sorted
STOP

**Comment by Himanshu40** [comment]
> Gotcha using insertion sort we could do that: Algorithm: START Step 1 : If it is the first element, it is already sorted. return 1; Step 2 : Pick next element Step 3 : Compare with all elements in the sorted sub-list Step 4 : Shift all the elements in the sorted sub-list that is less than the value to be sorted Step 5 : Insert the value Step 6 : Repeat until list is sorted STOP

I understand what you are trying to do but insertion sort is already there in Insertion_Sort/ dir. Have you looked into it? You can see other directories how the code files are there and how it is implemented.

**Pull request closed without merging**
